print("Wellcome to the Band Name Generator..")
# print("What is the name of the city you grow up in ?")
# city_name= input()
# print("What is your pet's name ?")
# pet_name= input()
# print("Your band name could be " + city_name + " " + pet_name)

city=input("What is the name of the city you grow up in ?\n")
pet=input("What is your pet's name ?\n")
print("Your band name could be " + city + " " + pet)